const SYLLABUS = {
    SEM1: {
        "With Electrical Science": [
            { name: "Applied Chemistry", credits: 3 },
            { name: "Applied Physics - I", credits: 3 },
            { name: "Electrical Science", credits: 3 },
            { name: "Applied Mathematics - I", credits: 4 },
            { name: "Indian Constitution", credits: 2 },
            { name: "Human Values and Ethics", credits: 1 },
            { name: "Manufacturing Process", credits: 4 },
            { name: "Physics - I Lab", credits: 1 },
            { name: "Applied Chemistry Lab", credits: 1 },
            { name: "Engineering Graphics - I", credits: 2 },
            { name: "Electrical Science Lab", credits: 1 },
        ],

        "With Environmental Studies": [
            { name: "Programming in 'C'", credits: 3 },
            { name: "Applied Physics - I", credits: 3 },
            { name: "Environmental Studies", credits: 3 },
            { name: "Applied Mathematics - I", credits: 4 },
            { name: "Communication Skills", credits: 3 },
            { name: "Manufacturing Process", credits: 4 },
            { name: "Physics - I Lab", credits: 1 },
            { name: "Programming in 'C' Lab", credits: 1 },
            { name: "Engineering Graphics - I", credits: 2 },
            { name: "Environmental Studies Lab", credits: 1 },
        ],
    },

    SEM3: {
        CSE: [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Discrete Mathematics", credits: 4 },
            { name: "Digital Logic and Computer Design", credits: 4 },
            { name: "Data Structures", credits: 4 },
            { name: "Object-Oriented Programming using C++", credits: 4 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Digital Logic and Computer Design Lab", credits: 1 },
            { name: "Data Structures Lab", credits: 1 },
            { name: "Object-Oriented Programming using C++ Lab", credits: 1 },
        ],

        "CSE-AI": [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Discrete Mathematics", credits: 4 },
            { name: "Digital Logic and Computer Design", credits: 4 },
            { name: "Data Structures", credits: 4 },
            { name: "Object-Oriented Programming using C++", credits: 4 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Digital Logic and Computer Design Lab", credits: 1 },
            { name: "Data Structures Lab", credits: 1 },
            { name: "Object-Oriented Programming using C++ Lab", credits: 1 },
        ],

        "CSE-AIML": [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Discrete Mathematics", credits: 4 },
            { name: "Digital Logic and Computer Design", credits: 4 },
            { name: "Data Structures", credits: 4 },
            { name: "Object-Oriented Programming using C++", credits: 4 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Digital Logic and Computer Design Lab", credits: 1 },
            { name: "Data Structures Lab", credits: 1 },
            { name: "Object-Oriented Programming using C++ Lab", credits: 1 },
        ],

        "CSE-DS": [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Discrete Mathematics", credits: 4 },
            { name: "Digital Logic and Computer Design", credits: 4 },
            { name: "Data Structures", credits: 4 },
            { name: "Object-Oriented Programming using C++", credits: 4 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Digital Logic and Computer Design Lab", credits: 1 },
            { name: "Data Structures Lab", credits: 1 },
            { name: "Object-Oriented Programming using C++ Lab", credits: 1 },
        ],

        CST: [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Discrete Mathematics", credits: 4 },
            { name: "Digital Logic and Computer Design", credits: 4 },
            { name: "Data Structures", credits: 4 },
            { name: "Object-Oriented Programming using C++", credits: 4 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Digital Logic and Computer Design Lab", credits: 1 },
            { name: "Data Structures Lab", credits: 1 },
            { name: "Object-Oriented Programming using C++ Lab", credits: 1 },
        ],

        ECE: [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Signal and System", credits: 3 },
            { name: "Digital Logic and Computer Design", credits: 4 },
            { name: "Analog Communications", credits: 4 },
            { name: "Analog Electronics-I", credits: 4 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Digital Logic and Computer Design Lab", credits: 1 },
            { name: "Analog Communications Lab", credits: 1 },
            { name: "Analog Electronics-I Lab", credits: 1 },
            { name: "Signal and System Lab", credits: 1 },
        ],

        "ECE-ACT": [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Signal and System", credits: 3 },
            { name: "Digital Logic and Computer Design", credits: 4 },
            { name: "Analog Communications", credits: 4 },
            { name: "Analog Electronics-I", credits: 4 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Digital Logic and Computer Design Lab", credits: 1 },
            { name: "Analog Communications Lab", credits: 1 },
            { name: "Analog Electronics-I Lab", credits: 1 },
            { name: "Signal and System Lab", credits: 1 },
        ],

        "EE-VLSI": [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Signal and System", credits: 3 },
            { name: "Digital Logic and Computer Design", credits: 4 },
            { name: "Analog Communications", credits: 4 },
            { name: "Analog Electronics-I", credits: 4 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Digital Logic and Computer Design Lab", credits: 1 },
            { name: "Analog Communications Lab", credits: 1 },
            { name: "Analog Electronics-I Lab", credits: 1 },
            { name: "Signal and System Lab", credits: 1 },
        ],

        EEE: [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Signals and Systems", credits: 3 },
            { name: "Electrical Materials", credits: 3 },
            { name: "Electrical Machines - I", credits: 4 },
            { name: "Electromagnetic Field Theory", credits: 3 },
            { name: "Electronics - I", credits: 3 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Electrical Machines - I Lab", credits: 1 },
            { name: "Electrical Engineering Workshop", credits: 1 },
            { name: "Electronics - I Lab", credits: 1 },
        ],

        IT: [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Discrete Mathematics", credits: 4 },
            { name: "Digital Logic and Computer Design", credits: 4 },
            { name: "Data Structures", credits: 4 },
            { name: "Object-Oriented Programming using C++", credits: 4 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Digital Logic and Computer Design Lab", credits: 1 },
            { name: "Data Structures Lab", credits: 1 },
            { name: "Object-Oriented Programming using C++ Lab", credits: 1 },
        ],

        ITE: [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Discrete Mathematics", credits: 4 },
            { name: "Digital Logic and Computer Design", credits: 4 },
            { name: "Data Structures", credits: 4 },
            { name: "Object-Oriented Programming using C++", credits: 4 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Digital Logic and Computer Design Lab", credits: 1 },
            { name: "Data Structures Lab", credits: 1 },
            { name: "Object-Oriented Programming using C++ Lab", credits: 1 },
        ],

        ME: [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Theory of Machines", credits: 4 },
            { name: "Strength of Materials", credits: 4 },
            { name: "Manufacturing Science and Technology - I", credits: 4 },
            { name: "Thermal Engineering - I", credits: 4 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Theory of Machines Lab", credits: 1 },
            { name: "Strength of Materials Lab", credits: 1 },
            { name: "Thermal Engineering - I Lab", credits: 1 },
            {
                name: "Manufacturing Science and Technology - I Lab",
                credits: 1,
            },
        ],

        MAE: [
            { name: "Computational Methods", credits: 4 },
            { name: "Indian Knowledge System", credits: 2 },
            { name: "Theory of Machines", credits: 4 },
            { name: "Strength of Materials", credits: 4 },
            { name: "Manufacturing Science and Technology - I", credits: 4 },
            { name: "Thermal Engineering - I", credits: 4 },
            { name: "Computational Methods Lab", credits: 1 },
            { name: "Theory of Machines Lab", credits: 1 },
            { name: "Strength of Materials Lab", credits: 1 },
            { name: "Thermal Engineering - I Lab", credits: 1 },
            {
                name: "Manufacturing Science and Technology - I Lab",
                credits: 1,
            },
        ],
    },
};
